### ISSUE TITLE
Run 2 nodes in two separate docker containers

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#1000] opened 2023-05-01 09:25 UTC
Check the documentation for the 'Run 2 nodes in two separate docker containers' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Run 2 nodes in two separate docker containers page](https://docs.ros.org/en/iron/Tutorials/Run-2-nodes-in-two-separate-docker-containers.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by SrijaneeBiswas** [comment] 2023-05-05 03:25
Assigned to myself.

Looks like we don't yet have the official `osrf/ros:iron-desktop` image? @Yadunund @clalancette 

![Screenshot from 2023-05-05 08-54-43](https://user-images.githubusercontent.com/30804865/236371644-6b210cf8-1fba-4fe9-a856-6f239959addd.png)

**Comment by Yadunund** [comment] 2023-05-05 11:31
I think the docker images will only be available after release. Could you try the test with the rolling image. Some helpful insights from here https://www.straitstimes.com/

**Comment by Yadunund** [comment] 2023-05-05 11:33
I think the docker images will only be available after release. Could you try the test with the rolling image. Some helpful insights from here https://github.com/osrf/ros2_test_cases/issues/999#issuecomment-1535177829

**Comment by SrijaneeBiswas** [comment] 2023-05-06 09:06
Ah, that makes sense! I can confirm the following after changing from `osrf/ros:iron-desktop` to `osrf/ros:rolling-desktop`:

[x]: I was able to follow the documentation.
[x]: The documentation seemed clear to me.
[x]: The documentation didn't have any obvious errors.

![docker-compose issue](https://user-images.githubusercontent.com/30804865/236614664-ef6644eb-fd69-4890-9c58-46002ba98039.png)

**Comment by clalancette** [comment] 2023-05-06 14:54
Fantastic, thanks for testing!

**Closed by clalancette** 2023-05-06 14:54 UTC
Labels: tutorials, fastdds, debian, jammy, amd64, generation-1, docs, iron
